Repository cbracken/rules_dart, pull requests merged in 2021-05, with the labels that each got.

#48 Update README to fix load statement
  README.md
Labels: bug

#52 Add testing via GitHub Actions
  .github/workflows/build.yml
  .travis.yml
  tools/install_deps.sh
Labels: enhancement, infra

#55 Add load directives for each rule type
  README.md
Labels: enhancement
